// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | TimelineYearSlice
  | TimelineTitleSlice
  | TimelineSubTitleSlice
  | TimelineParagraphSlice
  | TimelineImageSlice
  | TimelineSpacerSlice;

type AboutDocumentDataSlices2Slice = TeamMemberSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Skip to team button field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.skip_to_team_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skip_to_team_button: prismic.KeyTextField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
  /**
   * Team Section Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_section_title
   * - **Tab**: team members
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  team_section_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices2[]
   * - **Tab**: team members
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices2: prismic.SliceZone<AboutDocumentDataSlices2Slice>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type BlogPostDocumentDataSlicesSlice =
  | BlogPostSubTitleSlice
  | BlogPostParagraphSlice
  | BlogPostNoteSlice
  | BlogPostImageSlice
  | BlogPostBulletListSlice
  | BlogPostNumberedListSlice
  | BlogRichTextSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Route name(make this same as uid) field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.route_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  route_name: prismic.KeyTextField;

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Publish date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Read time(mins) field in *Blog Post*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.read_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  read_time: prismic.NumberField;

  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Preview image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.preview_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  preview_image: prismic.ImageField<never>;

  /**
   * Summary field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  summary: prismic.KeyTextField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type BlogsDocumentDataSlicesSlice = never;

/**
 * Content for Blogs documents
 */
interface BlogsDocumentData {
  /**
   * Slice Zone field in *Blogs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogs.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogs.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blogs document from Prismic
 *
 * - **API ID**: `blogs`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogsDocumentData>, "blogs", Lang>;

type CaseStudiesDocumentDataSlicesSlice = never;

/**
 * Content for Case Studies documents
 */
interface CaseStudiesDocumentData {
  /**
   * Slice Zone field in *Case Studies*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CaseStudiesDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: case_studies.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Case Studies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: case_studies.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Case Studies document from Prismic
 *
 * - **API ID**: `case_studies`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CaseStudiesDocumentData>,
    "case_studies",
    Lang
  >;

/**
 * Item in *Home → Dynamic Environment Card*
 */
export interface HomeDocumentDataDynamicEnvironmentCardItem {
  /**
   * Title field in *Home → Dynamic Environment Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.dynamic_environment_card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Home → Dynamic Environment Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.dynamic_environment_card[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Link Text field in *Home → Dynamic Environment Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.dynamic_environment_card[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link href field in *Home → Dynamic Environment Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.dynamic_environment_card[].link_href
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_href: prismic.KeyTextField;
}

/**
 * Item in *Home → Collision Card*
 */
export interface HomeDocumentDataCollisionCardItem {
  /**
   * Title field in *Home → Collision Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collision_card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Home → Collision Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collision_card[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Link Text field in *Home → Collision Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collision_card[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link href field in *Home → Collision Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collision_card[].link_href
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_href: prismic.KeyTextField;
}

/**
 * Item in *Home → Introducing Safety supervisor Card*
 */
export interface HomeDocumentDataIntroducingSafetySupervisorCardItem {
  /**
   * title field in *Home → Introducing Safety supervisor Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.introducing_safety_supervisor_card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Home → Introducing Safety supervisor Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.introducing_safety_supervisor_card[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * link text field in *Home → Introducing Safety supervisor Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.introducing_safety_supervisor_card[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link href field in *Home → Introducing Safety supervisor Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.introducing_safety_supervisor_card[].link_href
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_href: prismic.KeyTextField;
}

/**
 * Item in *Home → More Info about supervisor card*
 */
export interface HomeDocumentDataMoreInfoAboutSupervisorCardItem {
  /**
   * Title field in *Home → More Info about supervisor card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.more_info_about_supervisor_card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Home → More Info about supervisor card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.more_info_about_supervisor_card[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * link text field in *Home → More Info about supervisor card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.more_info_about_supervisor_card[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * link href field in *Home → More Info about supervisor card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.more_info_about_supervisor_card[].link_href
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_href: prismic.KeyTextField;
}

/**
 * Item in *Home → Metrics card*
 */
export interface HomeDocumentDataMetricsCardItem {
  /**
   * title field in *Home → Metrics card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.metrics_card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Home → Metrics card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.metrics_card[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * link text field in *Home → Metrics card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.metrics_card[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * link href field in *Home → Metrics card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.metrics_card[].link_href
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_href: prismic.KeyTextField;
}

/**
 * Item in *Home → Scroll to next section buttons*
 */
export interface HomeDocumentDataScrollToNextSectionButtonsItem {
  /**
   * Scroll Or Click To Explore field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].scroll_or_click_to_explore
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  scroll_or_click_to_explore: prismic.KeyTextField;

  /**
   * Enter Dynamic Environment field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].enter_dynamic_environment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  enter_dynamic_environment: prismic.KeyTextField;

  /**
   * Witness The Impact field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].witness_the_impact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  witness_the_impact: prismic.KeyTextField;

  /**
   * Face The Repercussions field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].face_the_repercussions
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  face_the_repercussions: prismic.KeyTextField;

  /**
   * Activate Safety Supervisor field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].activate_safety_supervisor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  activate_safety_supervisor: prismic.KeyTextField;

  /**
   * Reenter Dynamic Environment field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].reenter_dynamic_environment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reenter_dynamic_environment: prismic.KeyTextField;

  /**
   * Continue field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].continue
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  continue: prismic.KeyTextField;

  /**
   * Uncover Deeper Insights field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].uncover_deeper_insights
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uncover_deeper_insights: prismic.KeyTextField;

  /**
   * Explore Beyond field in *Home → Scroll to next section buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[].explore_beyond
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  explore_beyond: prismic.KeyTextField;
}

/**
 * Item in *Home → animation captions*
 */
export interface HomeDocumentDataAnimationCaptionsItem {
  /**
   * Collision field in *Home → animation captions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.animation_captions[].collision
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  collision: prismic.KeyTextField;

  /**
   * Down Time field in *Home → animation captions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.animation_captions[].down_time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  down_time: prismic.KeyTextField;

  /**
   * Activating field in *Home → animation captions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.animation_captions[].activating
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  activating: prismic.KeyTextField;

  /**
   * Activated field in *Home → animation captions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.animation_captions[].activated
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  activated: prismic.KeyTextField;

  /**
   * Obstacle Avoided field in *Home → animation captions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.animation_captions[].obstacle_avoided
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  obstacle_avoided: prismic.KeyTextField;
}

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Dynamic Environment Card field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.dynamic_environment_card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  dynamic_environment_card: prismic.GroupField<
    Simplify<HomeDocumentDataDynamicEnvironmentCardItem>
  >;

  /**
   * Collision Card field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collision_card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  collision_card: prismic.GroupField<
    Simplify<HomeDocumentDataCollisionCardItem>
  >;

  /**
   * Introducing Safety supervisor Card field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.introducing_safety_supervisor_card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  introducing_safety_supervisor_card: prismic.GroupField<
    Simplify<HomeDocumentDataIntroducingSafetySupervisorCardItem>
  >;

  /**
   * More Info about supervisor card field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.more_info_about_supervisor_card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  more_info_about_supervisor_card: prismic.GroupField<
    Simplify<HomeDocumentDataMoreInfoAboutSupervisorCardItem>
  >;

  /**
   * Metrics card field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.metrics_card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  metrics_card: prismic.GroupField<Simplify<HomeDocumentDataMetricsCardItem>>;

  /**
   * Scroll to next section buttons field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.scroll_to_next_section_buttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  scroll_to_next_section_buttons: prismic.GroupField<
    Simplify<HomeDocumentDataScrollToNextSectionButtonsItem>
  >;

  /**
   * animation captions field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.animation_captions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  animation_captions: prismic.GroupField<
    Simplify<HomeDocumentDataAnimationCaptionsItem>
  >;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PrivacyDocumentDataSlicesSlice =
  | PrivacyParagraghSlice
  | PrivacySubtitleSlice
  | PrivacyBulletListSlice;

/**
 * Content for Privacy documents
 */
interface PrivacyDocumentData {
  /**
   * Title field in *Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Privacy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacyDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Privacy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Privacy document from Prismic
 *
 * - **API ID**: `privacy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyDocumentData>,
    "privacy",
    Lang
  >;

type ProductDocumentDataSlicesSlice = never;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

type SecurityDocumentDataSlicesSlice =
  | SecurityParagraghSlice
  | SecuritySectionSlice
  | SecurityBulletListSlice;

/**
 * Content for Security documents
 */
interface SecurityDocumentData {
  /**
   * Title field in *Security*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: security.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Last Updated field in *Security*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: security.last_updated
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  last_updated: prismic.DateField;

  /**
   * Slice Zone field in *Security*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: security.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SecurityDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Security*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: security.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Security*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: security.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Security*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: security.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Security document from Prismic
 *
 * - **API ID**: `security`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SecurityDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SecurityDocumentData>,
    "security",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | BlogPostDocument
  | BlogsDocument
  | CaseStudiesDocument
  | HomeDocument
  | PrivacyDocument
  | ProductDocument
  | SecurityDocument;

/**
 * Primary content in *BlogPostBulletList → Items*
 */
export interface BlogPostBulletListSliceDefaultItem {
  /**
   * Title field in *BlogPostBulletList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_bullet_list.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *BlogPostBulletList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_bullet_list.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostBulletList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostBulletListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BlogPostBulletListSliceDefaultItem>
>;

/**
 * Slice variation for *BlogPostBulletList*
 */
type BlogPostBulletListSliceVariation = BlogPostBulletListSliceDefault;

/**
 * BlogPostBulletList Shared Slice
 *
 * - **API ID**: `blog_post_bullet_list`
 * - **Description**: BlogPostBulletList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostBulletListSlice = prismic.SharedSlice<
  "blog_post_bullet_list",
  BlogPostBulletListSliceVariation
>;

/**
 * Primary content in *BlogPostImage → Primary*
 */
export interface BlogPostImageSliceDefaultPrimary {
  /**
   * Image field in *BlogPostImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BlogPostImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostImage*
 */
type BlogPostImageSliceVariation = BlogPostImageSliceDefault;

/**
 * BlogPostImage Shared Slice
 *
 * - **API ID**: `blog_post_image`
 * - **Description**: BlogPostImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostImageSlice = prismic.SharedSlice<
  "blog_post_image",
  BlogPostImageSliceVariation
>;

/**
 * Primary content in *BlogPostNote → Primary*
 */
export interface BlogPostNoteSliceDefaultPrimary {
  /**
   * Text field in *BlogPostNote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_note.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostNote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostNoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostNote*
 */
type BlogPostNoteSliceVariation = BlogPostNoteSliceDefault;

/**
 * BlogPostNote Shared Slice
 *
 * - **API ID**: `blog_post_note`
 * - **Description**: BlogPostNote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNoteSlice = prismic.SharedSlice<
  "blog_post_note",
  BlogPostNoteSliceVariation
>;

/**
 * Primary content in *BlogPostNumberedList → Items*
 */
export interface BlogPostNumberedListSliceDefaultItem {
  /**
   * Title field in *BlogPostNumberedList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_numbered_list.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *BlogPostNumberedList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_numbered_list.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostNumberedList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNumberedListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BlogPostNumberedListSliceDefaultItem>
>;

/**
 * Slice variation for *BlogPostNumberedList*
 */
type BlogPostNumberedListSliceVariation = BlogPostNumberedListSliceDefault;

/**
 * BlogPostNumberedList Shared Slice
 *
 * - **API ID**: `blog_post_numbered_list`
 * - **Description**: BlogPostNumberedList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNumberedListSlice = prismic.SharedSlice<
  "blog_post_numbered_list",
  BlogPostNumberedListSliceVariation
>;

/**
 * Primary content in *BlogPostParagraph → Primary*
 */
export interface BlogPostParagraphSliceDefaultPrimary {
  /**
   * Text field in *BlogPostParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_paragraph.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostParagraph*
 */
type BlogPostParagraphSliceVariation = BlogPostParagraphSliceDefault;

/**
 * BlogPostParagraph Shared Slice
 *
 * - **API ID**: `blog_post_paragraph`
 * - **Description**: BlogPostParagraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostParagraphSlice = prismic.SharedSlice<
  "blog_post_paragraph",
  BlogPostParagraphSliceVariation
>;

/**
 * Primary content in *BlogPostSubTitle → Primary*
 */
export interface BlogPostSubTitleSliceDefaultPrimary {
  /**
   * Title field in *BlogPostSubTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_sub_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for BlogPostSubTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSubTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostSubTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostSubTitle*
 */
type BlogPostSubTitleSliceVariation = BlogPostSubTitleSliceDefault;

/**
 * BlogPostSubTitle Shared Slice
 *
 * - **API ID**: `blog_post_sub_title`
 * - **Description**: BlogPostSubTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSubTitleSlice = prismic.SharedSlice<
  "blog_post_sub_title",
  BlogPostSubTitleSliceVariation
>;

/**
 * Primary content in *BlogRichText → Primary*
 */
export interface BlogRichTextSliceDefaultPrimary {
  /**
   * text field in *BlogRichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_rich_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogRichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogRichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogRichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogRichText*
 */
type BlogRichTextSliceVariation = BlogRichTextSliceDefault;

/**
 * BlogRichText Shared Slice
 *
 * - **API ID**: `blog_rich_text`
 * - **Description**: BlogRichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogRichTextSlice = prismic.SharedSlice<
  "blog_rich_text",
  BlogRichTextSliceVariation
>;

/**
 * Primary content in *PrivacyBulletList → Primary*
 */
export interface PrivacyBulletListSliceDefaultPrimary {
  /**
   * Title field in *PrivacyBulletList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_bullet_list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *PrivacyBulletList → Items*
 */
export interface PrivacyBulletListSliceDefaultItem {
  /**
   * Bullet field in *PrivacyBulletList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_bullet_list.items[].bullet
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet: prismic.KeyTextField;
}

/**
 * Default variation for PrivacyBulletList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacyBulletListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivacyBulletListSliceDefaultPrimary>,
  Simplify<PrivacyBulletListSliceDefaultItem>
>;

/**
 * Slice variation for *PrivacyBulletList*
 */
type PrivacyBulletListSliceVariation = PrivacyBulletListSliceDefault;

/**
 * PrivacyBulletList Shared Slice
 *
 * - **API ID**: `privacy_bullet_list`
 * - **Description**: PrivacyBulletList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacyBulletListSlice = prismic.SharedSlice<
  "privacy_bullet_list",
  PrivacyBulletListSliceVariation
>;

/**
 * Primary content in *PrivacyParagraph → Primary*
 */
export interface PrivacyParagraghSliceDefaultPrimary {
  /**
   * Text field in *PrivacyParagraph → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_paragragh.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for PrivacyParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacyParagraghSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivacyParagraghSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivacyParagraph*
 */
type PrivacyParagraghSliceVariation = PrivacyParagraghSliceDefault;

/**
 * PrivacyParagraph Shared Slice
 *
 * - **API ID**: `privacy_paragragh`
 * - **Description**: PrivacyParagragh
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacyParagraghSlice = prismic.SharedSlice<
  "privacy_paragragh",
  PrivacyParagraghSliceVariation
>;

/**
 * Primary content in *PrivacySubtitle → Primary*
 */
export interface PrivacySubtitleSliceDefaultPrimary {
  /**
   * Subtitle field in *PrivacySubtitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_subtitle.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for PrivacySubtitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacySubtitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivacySubtitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivacySubtitle*
 */
type PrivacySubtitleSliceVariation = PrivacySubtitleSliceDefault;

/**
 * PrivacySubtitle Shared Slice
 *
 * - **API ID**: `privacy_subtitle`
 * - **Description**: PrivacySubtitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacySubtitleSlice = prismic.SharedSlice<
  "privacy_subtitle",
  PrivacySubtitleSliceVariation
>;

/**
 * Primary content in *SecurityNumberedList → Primary*
 */
export interface SecurityBulletListSliceDefaultPrimary {
  /**
   * Title field in *SecurityNumberedList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: security_bullet_list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *SecurityNumberedList → Items*
 */
export interface SecurityBulletListSliceDefaultItem {
  /**
   * Bullet field in *SecurityNumberedList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: security_bullet_list.items[].bullet
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet: prismic.KeyTextField;
}

/**
 * Default variation for SecurityNumberedList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecurityBulletListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecurityBulletListSliceDefaultPrimary>,
  Simplify<SecurityBulletListSliceDefaultItem>
>;

/**
 * Slice variation for *SecurityNumberedList*
 */
type SecurityBulletListSliceVariation = SecurityBulletListSliceDefault;

/**
 * SecurityNumberedList Shared Slice
 *
 * - **API ID**: `security_bullet_list`
 * - **Description**: SecurityBulletList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecurityBulletListSlice = prismic.SharedSlice<
  "security_bullet_list",
  SecurityBulletListSliceVariation
>;

/**
 * Primary content in *SecurityParagraph → Primary*
 */
export interface SecurityParagraghSliceDefaultPrimary {
  /**
   * Text field in *SecurityParagraph → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: security_paragragh.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for SecurityParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecurityParagraghSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecurityParagraghSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecurityParagraph*
 */
type SecurityParagraghSliceVariation = SecurityParagraghSliceDefault;

/**
 * SecurityParagraph Shared Slice
 *
 * - **API ID**: `security_paragragh`
 * - **Description**: SecurityParagragh
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecurityParagraghSlice = prismic.SharedSlice<
  "security_paragragh",
  SecurityParagraghSliceVariation
>;

/**
 * Primary content in *SecuritySection → Primary*
 */
export interface SecuritySectionSliceDefaultPrimary {
  /**
   * Title field in *SecuritySection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: security_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *SecuritySection → Items*
 */
export interface SecuritySectionSliceDefaultItem {
  /**
   * Paragraph field in *SecuritySection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: security_section.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for SecuritySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecuritySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecuritySectionSliceDefaultPrimary>,
  Simplify<SecuritySectionSliceDefaultItem>
>;

/**
 * Slice variation for *SecuritySection*
 */
type SecuritySectionSliceVariation = SecuritySectionSliceDefault;

/**
 * SecuritySection Shared Slice
 *
 * - **API ID**: `security_section`
 * - **Description**: SecuritySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecuritySectionSlice = prismic.SharedSlice<
  "security_section",
  SecuritySectionSliceVariation
>;

/**
 * Primary content in *TeamMember → Primary*
 */
export interface TeamMemberSliceDefaultPrimary {
  /**
   * Picture field in *TeamMember → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Position field in *TeamMember → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.primary.position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Name field in *TeamMember → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Bio field in *TeamMember → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.primary.bio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bio: prismic.KeyTextField;
}

/**
 * Default variation for TeamMember Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMemberSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamMemberSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamMember*
 */
type TeamMemberSliceVariation = TeamMemberSliceDefault;

/**
 * TeamMember Shared Slice
 *
 * - **API ID**: `team_member`
 * - **Description**: TeamMember
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMemberSlice = prismic.SharedSlice<
  "team_member",
  TeamMemberSliceVariation
>;

/**
 * Primary content in *TimelineImage → Primary*
 */
export interface TimelineImageSliceDefaultPrimary {
  /**
   * Image field in *TimelineImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TimelineImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineImage*
 */
type TimelineImageSliceVariation = TimelineImageSliceDefault;

/**
 * TimelineImage Shared Slice
 *
 * - **API ID**: `timeline_image`
 * - **Description**: TimelineImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineImageSlice = prismic.SharedSlice<
  "timeline_image",
  TimelineImageSliceVariation
>;

/**
 * Primary content in *TimelineParagraph → Primary*
 */
export interface TimelineParagraphSliceDefaultPrimary {
  /**
   * Text field in *TimelineParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_paragraph.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TimelineParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineParagraph*
 */
type TimelineParagraphSliceVariation = TimelineParagraphSliceDefault;

/**
 * TimelineParagraph Shared Slice
 *
 * - **API ID**: `timeline_paragraph`
 * - **Description**: TimelineParagraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineParagraphSlice = prismic.SharedSlice<
  "timeline_paragraph",
  TimelineParagraphSliceVariation
>;

/**
 * Primary content in *Spacer → Primary*
 */
export interface TimelineSpacerSliceDefaultPrimary {
  /**
   * Size field in *Spacer → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_spacer.primary.size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"small" | "medium" | "large">;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineSpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type TimelineSpacerSliceVariation = TimelineSpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `timeline_spacer`
 * - **Description**: TimelineSpacer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSpacerSlice = prismic.SharedSlice<
  "timeline_spacer",
  TimelineSpacerSliceVariation
>;

/**
 * Primary content in *TimelineSubTitle → Primary*
 */
export interface TimelineSubTitleSliceDefaultPrimary {
  /**
   * Subtitle field in *TimelineSubTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_sub_title.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for TimelineSubTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSubTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineSubTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineSubTitle*
 */
type TimelineSubTitleSliceVariation = TimelineSubTitleSliceDefault;

/**
 * TimelineSubTitle Shared Slice
 *
 * - **API ID**: `timeline_sub_title`
 * - **Description**: TimelineSubTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSubTitleSlice = prismic.SharedSlice<
  "timeline_sub_title",
  TimelineSubTitleSliceVariation
>;

/**
 * Primary content in *TimelineTitle → Primary*
 */
export interface TimelineTitleSliceDefaultPrimary {
  /**
   * Title field in *TimelineTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for TimelineTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineTitle*
 */
type TimelineTitleSliceVariation = TimelineTitleSliceDefault;

/**
 * TimelineTitle Shared Slice
 *
 * - **API ID**: `timeline_title`
 * - **Description**: TimelineTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineTitleSlice = prismic.SharedSlice<
  "timeline_title",
  TimelineTitleSliceVariation
>;

/**
 * Primary content in *TimelineYear → Primary*
 */
export interface TimelineYearSliceDefaultPrimary {
  /**
   * Year field in *TimelineYear → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_year.primary.year
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year: prismic.NumberField;
}

/**
 * Default variation for TimelineYear Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineYearSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineYearSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineYear*
 */
type TimelineYearSliceVariation = TimelineYearSliceDefault;

/**
 * TimelineYear Shared Slice
 *
 * - **API ID**: `timeline_year`
 * - **Description**: TimelineYear
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineYearSlice = prismic.SharedSlice<
  "timeline_year",
  TimelineYearSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AboutDocumentDataSlices2Slice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogsDocument,
      BlogsDocumentData,
      BlogsDocumentDataSlicesSlice,
      CaseStudiesDocument,
      CaseStudiesDocumentData,
      CaseStudiesDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PrivacyDocument,
      PrivacyDocumentData,
      PrivacyDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      SecurityDocument,
      SecurityDocumentData,
      SecurityDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogPostBulletListSlice,
      BlogPostBulletListSliceDefaultItem,
      BlogPostBulletListSliceVariation,
      BlogPostBulletListSliceDefault,
      BlogPostImageSlice,
      BlogPostImageSliceDefaultPrimary,
      BlogPostImageSliceVariation,
      BlogPostImageSliceDefault,
      BlogPostNoteSlice,
      BlogPostNoteSliceDefaultPrimary,
      BlogPostNoteSliceVariation,
      BlogPostNoteSliceDefault,
      BlogPostNumberedListSlice,
      BlogPostNumberedListSliceDefaultItem,
      BlogPostNumberedListSliceVariation,
      BlogPostNumberedListSliceDefault,
      BlogPostParagraphSlice,
      BlogPostParagraphSliceDefaultPrimary,
      BlogPostParagraphSliceVariation,
      BlogPostParagraphSliceDefault,
      BlogPostSubTitleSlice,
      BlogPostSubTitleSliceDefaultPrimary,
      BlogPostSubTitleSliceVariation,
      BlogPostSubTitleSliceDefault,
      BlogRichTextSlice,
      BlogRichTextSliceDefaultPrimary,
      BlogRichTextSliceVariation,
      BlogRichTextSliceDefault,
      PrivacyBulletListSlice,
      PrivacyBulletListSliceDefaultPrimary,
      PrivacyBulletListSliceDefaultItem,
      PrivacyBulletListSliceVariation,
      PrivacyBulletListSliceDefault,
      PrivacyParagraghSlice,
      PrivacyParagraghSliceDefaultPrimary,
      PrivacyParagraghSliceVariation,
      PrivacyParagraghSliceDefault,
      PrivacySubtitleSlice,
      PrivacySubtitleSliceDefaultPrimary,
      PrivacySubtitleSliceVariation,
      PrivacySubtitleSliceDefault,
      SecurityBulletListSlice,
      SecurityBulletListSliceDefaultPrimary,
      SecurityBulletListSliceDefaultItem,
      SecurityBulletListSliceVariation,
      SecurityBulletListSliceDefault,
      SecurityParagraghSlice,
      SecurityParagraghSliceDefaultPrimary,
      SecurityParagraghSliceVariation,
      SecurityParagraghSliceDefault,
      SecuritySectionSlice,
      SecuritySectionSliceDefaultPrimary,
      SecuritySectionSliceDefaultItem,
      SecuritySectionSliceVariation,
      SecuritySectionSliceDefault,
      TeamMemberSlice,
      TeamMemberSliceDefaultPrimary,
      TeamMemberSliceVariation,
      TeamMemberSliceDefault,
      TimelineImageSlice,
      TimelineImageSliceDefaultPrimary,
      TimelineImageSliceVariation,
      TimelineImageSliceDefault,
      TimelineParagraphSlice,
      TimelineParagraphSliceDefaultPrimary,
      TimelineParagraphSliceVariation,
      TimelineParagraphSliceDefault,
      TimelineSpacerSlice,
      TimelineSpacerSliceDefaultPrimary,
      TimelineSpacerSliceVariation,
      TimelineSpacerSliceDefault,
      TimelineSubTitleSlice,
      TimelineSubTitleSliceDefaultPrimary,
      TimelineSubTitleSliceVariation,
      TimelineSubTitleSliceDefault,
      TimelineTitleSlice,
      TimelineTitleSliceDefaultPrimary,
      TimelineTitleSliceVariation,
      TimelineTitleSliceDefault,
      TimelineYearSlice,
      TimelineYearSliceDefaultPrimary,
      TimelineYearSliceVariation,
      TimelineYearSliceDefault,
    };
  }
}
