// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | TimelineYearSlice
  | TimelineTitleSlice
  | TimelineSubTitleSlice
  | TimelineParagraphSlice
  | TimelineImageSlice
  | TimelineSpacerSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type BlogPostDocumentDataSlicesSlice =
  | BlogPostSubTitleSlice
  | BlogPostParagraphSlice
  | BlogPostNoteSlice
  | BlogPostImageSlice
  | BlogPostBulletListSlice
  | BlogPostNumberedListSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Route name(make this same as uid) field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.route_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  route_name: prismic.KeyTextField;

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Publish date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Read time(mins) field in *Blog Post*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.read_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  read_time: prismic.NumberField;

  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Preview image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.preview_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  preview_image: prismic.ImageField<never>;

  /**
   * Summary field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  summary: prismic.KeyTextField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | BlogPostDocument;

/**
 * Primary content in *BlogPostBulletList → Items*
 */
export interface BlogPostBulletListSliceDefaultItem {
  /**
   * Title field in *BlogPostBulletList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_bullet_list.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *BlogPostBulletList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_bullet_list.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostBulletList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostBulletListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BlogPostBulletListSliceDefaultItem>
>;

/**
 * Slice variation for *BlogPostBulletList*
 */
type BlogPostBulletListSliceVariation = BlogPostBulletListSliceDefault;

/**
 * BlogPostBulletList Shared Slice
 *
 * - **API ID**: `blog_post_bullet_list`
 * - **Description**: BlogPostBulletList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostBulletListSlice = prismic.SharedSlice<
  "blog_post_bullet_list",
  BlogPostBulletListSliceVariation
>;

/**
 * Primary content in *BlogPostImage → Primary*
 */
export interface BlogPostImageSliceDefaultPrimary {
  /**
   * Image field in *BlogPostImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BlogPostImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostImage*
 */
type BlogPostImageSliceVariation = BlogPostImageSliceDefault;

/**
 * BlogPostImage Shared Slice
 *
 * - **API ID**: `blog_post_image`
 * - **Description**: BlogPostImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostImageSlice = prismic.SharedSlice<
  "blog_post_image",
  BlogPostImageSliceVariation
>;

/**
 * Primary content in *BlogPostNote → Primary*
 */
export interface BlogPostNoteSliceDefaultPrimary {
  /**
   * Text field in *BlogPostNote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_note.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostNote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostNoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostNote*
 */
type BlogPostNoteSliceVariation = BlogPostNoteSliceDefault;

/**
 * BlogPostNote Shared Slice
 *
 * - **API ID**: `blog_post_note`
 * - **Description**: BlogPostNote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNoteSlice = prismic.SharedSlice<
  "blog_post_note",
  BlogPostNoteSliceVariation
>;

/**
 * Primary content in *BlogPostNumberedList → Items*
 */
export interface BlogPostNumberedListSliceDefaultItem {
  /**
   * Title field in *BlogPostNumberedList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_numbered_list.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *BlogPostNumberedList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_numbered_list.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostNumberedList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNumberedListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BlogPostNumberedListSliceDefaultItem>
>;

/**
 * Slice variation for *BlogPostNumberedList*
 */
type BlogPostNumberedListSliceVariation = BlogPostNumberedListSliceDefault;

/**
 * BlogPostNumberedList Shared Slice
 *
 * - **API ID**: `blog_post_numbered_list`
 * - **Description**: BlogPostNumberedList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostNumberedListSlice = prismic.SharedSlice<
  "blog_post_numbered_list",
  BlogPostNumberedListSliceVariation
>;

/**
 * Primary content in *BlogPostParagraph → Primary*
 */
export interface BlogPostParagraphSliceDefaultPrimary {
  /**
   * Text field in *BlogPostParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_paragraph.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogPostParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostParagraph*
 */
type BlogPostParagraphSliceVariation = BlogPostParagraphSliceDefault;

/**
 * BlogPostParagraph Shared Slice
 *
 * - **API ID**: `blog_post_paragraph`
 * - **Description**: BlogPostParagraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostParagraphSlice = prismic.SharedSlice<
  "blog_post_paragraph",
  BlogPostParagraphSliceVariation
>;

/**
 * Primary content in *BlogPostSubTitle → Primary*
 */
export interface BlogPostSubTitleSliceDefaultPrimary {
  /**
   * Title field in *BlogPostSubTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_sub_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for BlogPostSubTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSubTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostSubTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostSubTitle*
 */
type BlogPostSubTitleSliceVariation = BlogPostSubTitleSliceDefault;

/**
 * BlogPostSubTitle Shared Slice
 *
 * - **API ID**: `blog_post_sub_title`
 * - **Description**: BlogPostSubTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSubTitleSlice = prismic.SharedSlice<
  "blog_post_sub_title",
  BlogPostSubTitleSliceVariation
>;

/**
 * Primary content in *TimelineImage → Primary*
 */
export interface TimelineImageSliceDefaultPrimary {
  /**
   * Image field in *TimelineImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TimelineImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineImage*
 */
type TimelineImageSliceVariation = TimelineImageSliceDefault;

/**
 * TimelineImage Shared Slice
 *
 * - **API ID**: `timeline_image`
 * - **Description**: TimelineImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineImageSlice = prismic.SharedSlice<
  "timeline_image",
  TimelineImageSliceVariation
>;

/**
 * Primary content in *TimelineParagraph → Primary*
 */
export interface TimelineParagraphSliceDefaultPrimary {
  /**
   * Text field in *TimelineParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_paragraph.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TimelineParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineParagraph*
 */
type TimelineParagraphSliceVariation = TimelineParagraphSliceDefault;

/**
 * TimelineParagraph Shared Slice
 *
 * - **API ID**: `timeline_paragraph`
 * - **Description**: TimelineParagraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineParagraphSlice = prismic.SharedSlice<
  "timeline_paragraph",
  TimelineParagraphSliceVariation
>;

/**
 * Primary content in *Spacer → Primary*
 */
export interface TimelineSpacerSliceDefaultPrimary {
  /**
   * Size field in *Spacer → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_spacer.primary.size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"small" | "medium" | "large">;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineSpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type TimelineSpacerSliceVariation = TimelineSpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `timeline_spacer`
 * - **Description**: TimelineSpacer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSpacerSlice = prismic.SharedSlice<
  "timeline_spacer",
  TimelineSpacerSliceVariation
>;

/**
 * Primary content in *TimelineSubTitle → Primary*
 */
export interface TimelineSubTitleSliceDefaultPrimary {
  /**
   * Subtitle field in *TimelineSubTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_sub_title.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for TimelineSubTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSubTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineSubTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineSubTitle*
 */
type TimelineSubTitleSliceVariation = TimelineSubTitleSliceDefault;

/**
 * TimelineSubTitle Shared Slice
 *
 * - **API ID**: `timeline_sub_title`
 * - **Description**: TimelineSubTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSubTitleSlice = prismic.SharedSlice<
  "timeline_sub_title",
  TimelineSubTitleSliceVariation
>;

/**
 * Primary content in *TimelineTitle → Primary*
 */
export interface TimelineTitleSliceDefaultPrimary {
  /**
   * Title field in *TimelineTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for TimelineTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineTitle*
 */
type TimelineTitleSliceVariation = TimelineTitleSliceDefault;

/**
 * TimelineTitle Shared Slice
 *
 * - **API ID**: `timeline_title`
 * - **Description**: TimelineTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineTitleSlice = prismic.SharedSlice<
  "timeline_title",
  TimelineTitleSliceVariation
>;

/**
 * Primary content in *TimelineYear → Primary*
 */
export interface TimelineYearSliceDefaultPrimary {
  /**
   * Year field in *TimelineYear → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_year.primary.year
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year: prismic.NumberField;
}

/**
 * Default variation for TimelineYear Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineYearSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineYearSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimelineYear*
 */
type TimelineYearSliceVariation = TimelineYearSliceDefault;

/**
 * TimelineYear Shared Slice
 *
 * - **API ID**: `timeline_year`
 * - **Description**: TimelineYear
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineYearSlice = prismic.SharedSlice<
  "timeline_year",
  TimelineYearSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogPostBulletListSlice,
      BlogPostBulletListSliceDefaultItem,
      BlogPostBulletListSliceVariation,
      BlogPostBulletListSliceDefault,
      BlogPostImageSlice,
      BlogPostImageSliceDefaultPrimary,
      BlogPostImageSliceVariation,
      BlogPostImageSliceDefault,
      BlogPostNoteSlice,
      BlogPostNoteSliceDefaultPrimary,
      BlogPostNoteSliceVariation,
      BlogPostNoteSliceDefault,
      BlogPostNumberedListSlice,
      BlogPostNumberedListSliceDefaultItem,
      BlogPostNumberedListSliceVariation,
      BlogPostNumberedListSliceDefault,
      BlogPostParagraphSlice,
      BlogPostParagraphSliceDefaultPrimary,
      BlogPostParagraphSliceVariation,
      BlogPostParagraphSliceDefault,
      BlogPostSubTitleSlice,
      BlogPostSubTitleSliceDefaultPrimary,
      BlogPostSubTitleSliceVariation,
      BlogPostSubTitleSliceDefault,
      TimelineImageSlice,
      TimelineImageSliceDefaultPrimary,
      TimelineImageSliceVariation,
      TimelineImageSliceDefault,
      TimelineParagraphSlice,
      TimelineParagraphSliceDefaultPrimary,
      TimelineParagraphSliceVariation,
      TimelineParagraphSliceDefault,
      TimelineSpacerSlice,
      TimelineSpacerSliceDefaultPrimary,
      TimelineSpacerSliceVariation,
      TimelineSpacerSliceDefault,
      TimelineSubTitleSlice,
      TimelineSubTitleSliceDefaultPrimary,
      TimelineSubTitleSliceVariation,
      TimelineSubTitleSliceDefault,
      TimelineTitleSlice,
      TimelineTitleSliceDefaultPrimary,
      TimelineTitleSliceVariation,
      TimelineTitleSliceDefault,
      TimelineYearSlice,
      TimelineYearSliceDefaultPrimary,
      TimelineYearSliceVariation,
      TimelineYearSliceDefault,
    };
  }
}
