import clsx from "clsx";
import "./globals.css";
import "../../public/fonts.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// import { Manrope, Roboto_Mono } from 'next/font/google'
import Header from "@/components/Header";
import { manrope } from "./fonts";
import Footer from "@/components/Footer";
import Head from "next/head";

// const manrope = Manrope({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-manrope',
// })

// const roboto_mono = Roboto_Mono({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-roboto-mono',
// })

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={manrope.className}>
            <Head>
                <link
                    rel="apple-touch-icon"
                    sizes="180x180"
                    href="/apple-touch-icon.png"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="32x32"
                    href="/favicon-32x32.png"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="16x16"
                    href="/favicon-16x16.png"
                />
                <link rel="manifest" href="/site.webmanifest" />
                <link
                    rel="mask-icon"
                    href="/safari-pinned-tab.svg"
                    color="#008ea1"
                />
                <meta name="msapplication-TileColor" content="#2b5797" />
                <meta name="theme-color" content="#141415" />
            </Head>
            <body
                style={{
                    background: "#151516",
                    color: "white",
                }}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
