import clsx from 'clsx'
import './globals.css'
import '../../public/fonts.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// import { Manrope, Roboto_Mono } from 'next/font/google'
import Header from '@/components/Header'
import { manrope } from './fonts'
 
// const manrope = Manrope({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-manrope',
// })
 
// const roboto_mono = Roboto_Mono({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-roboto-mono',
// })
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={manrope.className}>
      <body style={{
        background: '#0b0b0b',
        color: "white",
      }}>
        <Header/>
        {children}
        </body>
    </html>
  )
}