// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_post_bullet_list: dynamic(() => import("./BlogPostBulletList")),
  blog_post_image: dynamic(() => import("./BlogPostImage")),
  blog_post_note: dynamic(() => import("./BlogPostNote")),
  blog_post_numbered_list: dynamic(() => import("./BlogPostNumberedList")),
  blog_post_paragraph: dynamic(() => import("./BlogPostParagraph")),
  blog_post_sub_title: dynamic(() => import("./BlogPostSubTitle")),
  blog_rich_text: dynamic(() => import("./BlogRichText")),
  privacy_bullet_list: dynamic(() => import("./PrivacyBulletList")),
  privacy_paragragh: dynamic(() => import("./PrivacyParagraph")),
  privacy_subtitle: dynamic(() => import("./PrivacySubtitle")),
  security_bullet_list: dynamic(() => import("./SecurityNumberedList")),
  security_paragragh: dynamic(() => import("./SecurityParagraph")),
  security_section: dynamic(() => import("./SecuritySection")),
  team_member: dynamic(() => import("./TeamMember")),
  timeline_image: dynamic(() => import("./TimelineImage")),
  timeline_paragraph: dynamic(() => import("./TimelineParagraph")),
  timeline_spacer: dynamic(() => import("./Spacer")),
  timeline_sub_title: dynamic(() => import("./TimelineSubTitle")),
  timeline_title: dynamic(() => import("./TimelineTitle")),
  timeline_year: dynamic(() => import("./TimelineYear")),
};
